### ISSUE TITLE
Total fix

### ISSUE THREAD

**Issue by Annabelx61** [Annabelx61/to-dont-list#1]
The code currently adds the prices of the grocery. If you have 2 or more of the same item you will need to add it twice or more to the cart (list). What needs to be fixed is that the program should count the number of the same items using the elevated button which will be used to sum up the total. 

Instead of 
1. Egg 
2. Egg 
3. Milk 

Total = Egg_price + Egg_price + Milk

It should be 
2 Eggs
1 Milk

Total = 2*Egg_price + Milk_price

**Comment by SamCT6** [comment]
I can work on this one.
